# Generated by Django 5.2.5 on 2025-11-04 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('capacidad', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacidad (uom)')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'indexes': [models.Index(fields=['nombre'], name='transaction_nombre_deebb1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Cantidad')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mov_ingreso', to='transactional.bodega', verbose_name='Bodega destino')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mov_salida', to='transactional.bodega', verbose_name='Bodega origen')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='products.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tipo', 'fecha'], name='transaction_tipo_6e9cb0_idx'), models.Index(fields=['producto'], name='transaction_product_66825e_idx'), models.Index(fields=['bodega_origen'], name='transaction_bodega__b83f02_idx'), models.Index(fields=['bodega_destino'], name='transaction_bodega__c5f569_idx'), models.Index(fields=['lote'], name='transaction_lote_a0f54e_idx'), models.Index(fields=['serie'], name='transaction_serie_ca4b12_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote')),
                ('serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Cantidad')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='transactional.bodega', verbose_name='Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'indexes': [models.Index(fields=['producto', 'bodega'], name='transaction_product_a2afbf_idx'), models.Index(fields=['lote'], name='transaction_lote_8e0c65_idx'), models.Index(fields=['serie'], name='transaction_serie_08ed26_idx'), models.Index(fields=['fecha_vencimiento'], name='transaction_fecha_v_89ce1f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='stock_cantidad_ge_0')],
                'unique_together': {('producto', 'bodega', 'lote', 'serie', 'fecha_vencimiento')},
            },
        ),
    ]
