# Generated by Django 5.2.5 on 2025-11-04 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_usuario_mfa_habilitado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(blank=True, max_length=120, verbose_name='Área/Unidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mfa_habilitado',
            field=models.BooleanField(default=False, verbose_name='MFA habilitado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default=56900000000, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{6,30}$', 'Teléfono inválido')], verbose_name='Teléfono'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='users_usuar_usernam_7bc35f_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='users_usuar_email_af433f_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['activo'], name='users_usuar_activo_ffa8ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('activo__in', [True, False])), name='usr_activo_bool'),
        ),
    ]
